### ISSUE TITLE
Peer to peer review 12/06/2022

### ISSUE THREAD

**Issue by Ramaunspoken** [MNisarAli/1st-Capstone-Conference-page#3]
In the main program, session consider switching your on-hover effect from border to outline on line 416.
The text and Image were not aligned I think it would look better if you aligned the image and the text.

**Comment by MNisarAli** [comment]
> In the main program, session consider switching your on-hover effect from border to outline on line 416. The text and Image were not aligned I think it would look better if you aligned the image and the text.

Hi @Ramaunspoken, thank you 🙏 so much for the review. I will work on the suggestion you mentioned. Again, thank you a lot 😄.
